version: '3'

services:
  nodeapp:
    container_name: nodeapp
    build: .
    command: "yarn run dev"
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - nodedb
    volumes:
      - .:/usr/src/app

  nodedb:
    image: mongo
    container_name: nodedb
    ports:
      - "27017:27017"
